package Clases;
// Generated Jan 4, 2017 12:51:37 AM by Hibernate Tools 4.3.1



/**
 * CobroActividad generated by hbm2java
 */
public class CobroActividad  implements java.io.Serializable {


     private int id;
     private int idCobro;
     private int idActividad;
     private int cantidad;

    public CobroActividad() {
    }

    public CobroActividad(int id, int idCobro, int idActividad, int cantidad) {
       this.id = id;
       this.idCobro = idCobro;
       this.idActividad = idActividad;
       this.cantidad = cantidad;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getIdCobro() {
        return this.idCobro;
    }
    
    public void setIdCobro(int idCobro) {
        this.idCobro = idCobro;
    }
    public int getIdActividad() {
        return this.idActividad;
    }
    
    public void setIdActividad(int idActividad) {
        this.idActividad = idActividad;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }




}


