package Clases;
// Generated Jan 4, 2017 12:51:37 AM by Hibernate Tools 4.3.1



/**
 * CobroActividad generated by hbm2java
 */
public class CobroActividad  implements java.io.Serializable {


     private int id;
     private int idCobro;
     private Actividad actividad;
     private int cantidad;
     private float importe;

    public CobroActividad() {
    }

    public CobroActividad(int id, int idCobro, Actividad actividad, int cantidad) {
        this.id = id;
        this.idCobro = idCobro;
        this.actividad = actividad;
        this.cantidad = cantidad;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getIdCobro() {
        return this.idCobro;
    }
    
    public void setIdCobro(int idCobro) {
        this.idCobro = idCobro;
    }

    public Actividad getActividad() {
        return actividad;
    }

    public void setActividad(Actividad actividad) {
        if(actividad!=null){
            setImporte(actividad.getPrecio()*cantidad);
        }
        this.actividad = actividad;
    }
    
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        if(actividad!=null){
            setImporte(actividad.getPrecio()*cantidad);
        }
        this.cantidad = cantidad;
    }

    public float getImporte() {
        return importe;
    }

    public void setImporte(float importe) {
        this.importe = importe;
    }

}


