package Clases;
// Generated Jan 4, 2017 12:51:37 AM by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import org.hibernate.Hibernate;




/**
 * Cobro generated by hbm2java
 */
public class Cobro  implements java.io.Serializable {


     private int id;
     private String fecha;
     private float importe;
     private float pago;
     private float adeuda;
     private String comprobante;
     private Cliente cliente;
     private List<CobroActividad> cobroActividad = new ArrayList();


    public Cobro() {
    }

    public Cobro(int id, String fecha, float importe, float pago, float adeuda, String comprobante, Cliente cliente) {
        this.id = id;
        this.fecha = fecha;
        this.importe = importe;
        this.pago = pago;
        this.adeuda = adeuda;
        this.comprobante = comprobante;
        this.cliente = cliente;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getFecha() {
        return this.fecha;
    }
    
    public void setFecha(String fecha) {
        this.fecha = fecha;
    }
    public float getImporte() {
        return this.importe;
    }
    
    public void setImporte(float importe) {
        this.importe = importe;
    }
    public float getPago() {
        return this.pago;
    }
    
    public void setPago(float pago) {
        this.pago = pago;
    }
    public float getAdeuda() {
        return this.adeuda;
    }
    
    public void setAdeuda(float adeuda) {
        this.adeuda = adeuda;
    }
    public String getComprobante() {
        return this.comprobante;
    }
    
    public void setComprobante(String comprobante) {
        this.comprobante = comprobante;
    }

    public Cliente getCliente() {
        return cliente;
    }

    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

    public List<CobroActividad> getCobroActividad() {
        return cobroActividad;
    }

    public void setCobroActividad(List<CobroActividad> cobroActividad) {
        this.cobroActividad = cobroActividad;
    }

}


